config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      get :join_event
    end
  end
  root to: 'static_pages#landing'
  get 'landing', to: 'static_pages#landing'
  get 'selection', to: 'static_pages#selection'
  get 'sign', to: 'jios#new'
  get 'new', to: 'events#new'
  get 'list', to: 'events#index'

  resources :jios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :timelimit, numericality: {only_integer: true}
  belongs_to :jio
  has_many :joiners
   has_many :jios, through: :joiners
  def time_left
    (created_at + timelimit.minutes)
  end
end

app/models/jio.rb
class Jio < ApplicationRecord
  has_many :joiners
  has_many :events, through: :joiners
end

app/models/joiner.rb
class Joiner < ApplicationRecord
  belongs_to :jio
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:join_event, :show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end
  
  def expiry
    @event.created_at + timelimit.minutes
  end
  
  def new
    @event = Event.new
  end
  
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @event.update(expiry: @event.created_at+@event.timelimit.minutes )
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def join_event
    user = Jio.find(session[:jios])
    if user == @event.jio
      redirect_to @event, notice: "You have already joined this event."
    elsif user.in? @event.jios 
      redirect_to @event, notice: "You have already joined this event."
    else 
      @event.jios << user
      redirect_to @event, notice: "Thanks for joining."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :location, :grouppax, :timelimit, :jio_id)
    end
end

app/controllers/jios_controller.rb
class JiosController < ApplicationController
  before_action :set_jio, only: [:show, :edit, :update, :destroy]

  # GET /static_pages/landing
  # GET /static_pages/landing.json
  def landing
  end

  # GET /jios/1
  # GET /jios/1.json
  def show
  end

  # GET /jios/new
  def new
    @jio = Jio.new
  end

  # GET /jios/1/edit
  def edit
  end

  # POST /jios
  # POST /jios.json
  def create
    @jio = Jio.new(jio_params)

    respond_to do |format|
      if @jio.save
        session[:jios] = @jio.id
        format.html { render :template => "static_pages/selection"  }
        format.json { render :show, status: :created, location: @jio }
      else
        format.html { render :new }
        format.json { render json: @jio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jios/1
  # PATCH/PUT /jios/1.json
  def update
    respond_to do |format|
      if @jio.update(jio_params)
        format.html { redirect_to @jio, notice: 'Jio was successfully updated.' }
        format.json { render :show, status: :ok, location: @jio }
      else
        format.html { render :edit }
        format.json { render json: @jio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jios/1
  # DELETE /jios/1.json
  def destroy
    @jio.destroy
    respond_to do |format|
      format.html { redirect_to jios_url, notice: 'Jio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jio
      @jio = Jio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jio_params
      params.require(:jio).permit(:name, :contact_number)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
    
  end

  def selection
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jios_helper.rb
module JiosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :grouppax %>
    <%= form.number_field :grouppax %>
  </div>

  <div class="field">
    <%= form.label :timelimit %>
    <%= form.number_field :timelimit %>
  </div>

  <div class="field">
    <%= form.label :jio_id %>
    <%= form.text_field :jio_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/event.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
<div class="modal-dialog" style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -65%);">
		<p style="text-align:left;font-family: 'Amatic SC', cursive; font-size: 30px; font-weight: 300; color: #FFFFFF;">Event List</p>
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-body">
					<table class="table table-hover">
					  <tr>

					  <th>Name</th>
					  <th>Description</th>
					  <th>Location</th>
					  <th>Time Left</th>
					  </tr>
					  <tr>
					  <td><%= @event.name %></td>
					  <td><%= @event.description %></td>
					  <td><%= @event.location %></td>
					  <td><%= x = (@event.created_at+@event.timelimit.minutes) - Time.now  %></td>
					  </tr>
					  
					</table>
					</br>
				</div>
			</div>
		</div>
		
		<div class="icon">
			<img src="<%= image_path("joiw.png")%>" style="width:12%; "/>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>

		<script>
		// Set the date we're counting down to
			var quote = "<%= x = @event.created_at+@event.timelimit.minutes %>";
		var countDownDate = new Date(quote).getTime();

		// Update the count down every 1 second
		var x = setInterval(function() {

			// Get todays date and time
			var now = new Date().getTime();

			// Find the distance between now an the count down date
			var distance = countDownDate - now;

			// Time calculations for days, hours, minutes and seconds
			var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
			var seconds = Math.floor((distance % (1000 * 60)) / 1000);

			// Display the result in the element with id="demo"
			document.getElementById("time").innerHTML = minutes + "m " + seconds + "s ";

			// If the count down is finished, write some text 
			if (distance < 0) {
				clearInterval(x);
				document.getElementById("time").innerHTML = "EXPIRED";
				document.getElementById("title").innerHTML = "Event Started/ Ended";
			}
		}, 1000);
		</script>

app/views/events/index.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
<div class="modal-dialog" style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -65%); z-index: 100">
		<p style="text-align:left;font-family: 'Amatic SC', cursive; font-size: 30px; font-weight: 300; color: #FFFFFF;">Event List</p>
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-body">
					<table class="table table-hover">
					  <tr>

					  <th>Name</th>
					  <th>Description</th>
					  <th>Location</th>
					  <th>Time Left</th>
             <th>Action</th>
					  </tr>
            <% @events.each do |event| %>
              <% next if (event.created_at + event.timelimit.minutes) < Time.now %>
              <tr>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.location %></td>
              <td><%= time_ago_in_words(event.time_left)  %></td>
              <td><%= link_to 'join', join_event_event_path(event.id)  %></td>  
              </tr>
            <% end %>
					  
					</table>
					</br>
				</div>
			</div>
		</div>
		
		<div class="icon">
			<img src="<%= image_path("joiw.png")%>" style="width:12%; "/>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>

app/views/events/new.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
		<div class="modal-dialog" style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -65%); z-index: 100">
		<p style="text-align:left;font-family: 'Amatic SC', cursive; font-size: 30px; font-weight: 300; color: #FFFFFF;">Create Event</p>
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-body">
          <%= form_with(model: @event, local: true) do |form| %>
            <% if @event.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

                <ul>
                <% @event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
          
          
            <%= form.hidden_field :jio_id, value: session[:jios], class:"form-group type" %>
          
					<div class="form-group">
              <%= form.label :name, class:"form-group label" %>
              <%= form.text_field :name, class:"form-group type" %>
            </div>
				
				<div class="form-group">
              <%= form.label :description, class:"form-group label" %>
              <%= form.text_field :description, class:"form-group type" %>
            </div>
				
				<div class="form-group">
              <%= form.label :location, class:"form-group label" %>
              <%= form.text_field :location, class:"form-group type" %>
            </div>
          
        <div class="form-group">
            <%= form.label :grouppax, class:"form-group label" %>
            <%= form.text_field :grouppax, class:"form-group type" %>
          </div>
          
        <div class="form-group">
              <%= form.label :timelimit, class:"form-group label" %>
              <%= form.text_field :timelimit, class:"form-group type" %>
            </div>
				
				<div class="modal-footer">
              <%= link_to 'Back', landing_path, class:"btn btn-default" %>              
              <div class="actions">
                <!---<%= link_to 'Confirm', selection_path, class:"btn btn-default" %>--->
                <%= form.submit "Comfirm", class: "btn btn-default" %>
              </div>
            </div>
          <% end %>
          </div>
			</div>
		</div>
		
		<div class="icon">
			<img src="<%= image_path("invw.png")%>" style="width:12%; "/>
			<p class="icon">Inviter</p>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>

app/views/events/show.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
<div class="modal-dialog" style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -65%);">
		<p id="title" style="text-align:left;font-family: 'Amatic SC', cursive; font-size: 30px; font-weight: 300; color: #FFFFFF;">Waiting for event...</p>
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-body">
					<p id="time" style="text-align:center;font-family: 'Amatic SC', cursive; font-size: 70px; color: #000000;margin:20px;"></p>
					</br>
					<table class="table table-hover">
					  <tr>
					  <th>Name</th>
					  <td>:</td>
					  <td><%= @event.name %></td>
					  </tr>
					  <tr>
					  <th>Description</th>
					  <td>:</td>
					  <td><%= @event.description %></td>
					  </tr>
					  <tr>
					  <th>Location</th>
					  <td>:</td>
					  <td><%= @event.location %></td>
					  </tr>
					</table>
					</br>
					<table class="table table-hover">
					  <tr>
					  <th>Name</th>
					  <th>Contact</th>
					  </tr>
					  <tr>
					  <td><%= @event.jio.name %></td>
					  <td><%= @event.jio.contact_number %></td>
					  </tr>
						<% @event.jios.each do |jio| %>
					  <tr>
					  <td><%= jio.name %></td>
					  <td><%= jio.contact_number %></td>
					  </tr>
						<% end %>
					</table>
					</br>
				</div>
			</div>
		</div>
		
		<div class="icon">
			<img src="<%= image_path("joiw.png")%>" style="width:12%; "/>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>

		<script>
		// Set the date we're counting down to
			var quote = "<%= x = @event.created_at+@event.timelimit.minutes %>";
		var countDownDate = new Date(quote).getTime();

		// Update the count down every 1 second
		var x = setInterval(function() {

			// Get todays date and time
			var now = new Date().getTime();

			// Find the distance between now an the count down date
			var distance = countDownDate - now;

			// Time calculations for days, hours, minutes and seconds
			var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
			var seconds = Math.floor((distance % (1000 * 60)) / 1000);

			// Display the result in the element with id="demo"
			document.getElementById("time").innerHTML = minutes + "m " + seconds + "s ";

			// If the count down is finished, write some text 
			if (distance < 0) {
				clearInterval(x);
				document.getElementById("time").innerHTML = "Time's Up";
				document.getElementById("title").innerHTML = "Event Started/ Ended";
			}
		}, 1000);
		</script>

app/views/home/index.html.erb
<h1>InstantVite</h1>
<%= link_to 'interviewer1', invite_path(@jio)%>
<%= link_to 'Invite!', invite_path  %>
<%= link_to 'Join!!!', join_path %>

app/views/jios/_form.html.erb
<%= form_with(model: @jio, local: true) do |form| %>
  <% if @jio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jio.errors.count, "error") %> prohibited this jio from being saved:</h2>

      <ul>
      <% @jio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.l/abel :event %>
    <%= form.text_field :event %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :time_limit %>
    <%= form.text_field :time_limit %>
  </div>

  <div class="field">
    <%= form.label :max_pax %>
    <%= form.text_field :max_pax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jios/_form2.html.erb
<%= form_with(model: jio, local: true) do |form| %>
  <% if jio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jio.errors.count, "error") %> prohibited this jio from being saved:</h2>

      <ul>
      <% jio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jios/edit.html.erb
<h1>Editing Jio</h1>

<%= render 'form', jio: @jio %>

<%= link_to 'Show', @jio %> |
<%= link_to 'Back', jios_path %>

app/views/jios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jios.each do |jio| %>
      <tr>
        <td><%= jio.name %></td>
        <td><%= jio.contact_number %></td>
        <td><%= link_to 'Show', jio %></td>
        <td><%= link_to 'Edit', edit_jio_path(jio) %></td>
        <td><%= link_to 'Destroy', jio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jio', new_jio_path %>

app/views/jios/inviter1.html.erb
<h1>Invite Details</h1>

<%= render 'form', jio: @jio %>

<%= link_to 'Show', @jio %> |
<%= link_to 'Back', jios_path %>

app/views/jios/joiner1.html.erb
<p id="notice"><%= notice %></p>

<h1>Jios</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Description</th>
      <th>Location</th>
      <th>Time limit</th>
      <th>Max pax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jios.each do |jio| %>
      <tr>
        <td><%= jio.event %></td>
        <td><%= jio.description %></td>
        <td><%= jio.location %></td>
        <td><%= jio.time_limit %></td>
        <td><%= jio.max_pax %></td>
        <td><%= link_to 'Show', jio %></td>
        <td><%= link_to 'Edit', edit_jio_path(jio) %></td>
        <td><%= link_to 'Destroy', jio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', new_jio_path %>

app/views/jios/login.html.erb
<p id="notice"><%= notice %></p>

<h1>Login Page</h1>

<%= render 'form2', jio: @jio %>

<br>

<%= link_to 'Back', new_jio_path %>

app/views/jios/new.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
		<div class="modal-dialog" style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -65%);">
		<p style="text-align:left;font-family: 'Amatic SC', cursive; font-size: 30px; font-weight: 300; color: #FFFFFF;">Sign Up</p>
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-body">
          <%= form_with(model: @jio, local: true) do |form| %>
           <% if @jio.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@jio.errors.count, "error") %> prohibited this jio from being saved:</h2>

                <ul>
                <% @jio.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :name, class:"form-group label" %>
              <%= form.text_field :name, class:"form-group type" %>
            </div>

            <div class="form-group">
              <%= form.label :contact_number, class:"form-group label"%>
              <%= form.text_field :contact_number, class:"form-group type" %>
            </div>
            
            <div class="modal-footer">
              <%= link_to 'Back', landing_path, class:"btn btn-default" %>              
              <div class="actions">
<!--                 <% link_to 'Confirm', selection_path, class:"btn btn-default" %> -->
               <%= form.submit "Submit", class: "btn btn-default" %>
              </div>
            </div>
          <% end %>
				
				</div>
			</div>
		</div>
		
		<div class="icon">
			<img src="<%= image_path("pplw.png")%>" style="width:12%; "/>
			<p class="icon">Sign Up</p>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>
		
		
	</div>

app/views/jios/show.html.erb
<!---<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jio.name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @jio.contact_number %>
</p>

<%= link_to 'Edit', edit_jio_path(@jio) %> |
<%= link_to 'Back', jios_path %>--->

<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
<div class="row" style="margin:5%;">	
		<div class="col-sm-5" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 50px;
	font-weight: 300;
	color: #FFFFFF;">
        <%= link_to image_tag("invw.png"), new_path, class: "images" %>
			</div>
			<div class="col-sm-2" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 150px;
	font-weight: 300;
	color: #FFFFFF;">
				<p></p>
			</div>
			<div class="col-sm-5" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 50px;
	font-weight: 300;
	color: #FFFFFF; margin-top:20px;">
        <%= link_to image_tag("joiw.png"), landing_path, class: "images" %>
			</div>
	</div>
<div class="row" style="margin: 2%; margin-left: -15px;">	
		<div class="col-sm-5" style="text-align:center;">
				<%= link_to 'Be an Inviter', new_path, class:"btn btn-default" %>
			</div>
			<div class="col-sm-2" style="text-align:center;">
				<p></p>
			</div>
			<div class="col-sm-5" style="text-align:center;">
				<%= link_to 'Be a Joiner', landing_path, class:"btn btn-default" %>
			</div>
	</div>
		
		<div class="col-sm-12">
      </br>
			<p style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 80px;
	font-weight: 300;
	color: #FFFFFF;">InstantVite</p>
      <% = @jio.name %>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FutureHack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag   "bootstrap.css", media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag  "index.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  "form.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/landing.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>

<div class="col-sm-12"  style="top: 50%; position: fixed; left: 50%; transform: translate(-50%, -60%);">
			<p style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 80px;
	font-weight: 300;
	color: #FFFFFF;margin:5%;">InstantVite</p>
			<p style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 40px;
	font-weight: 300;
	color: #FFFFFF;margin:5%;"> - Don't say we don't jio you ahh... -</p>    
      <p style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 40px;
	font-weight: 300;
	color: #FFFFFF;margin:5%;"><%= link_to 'Continue', sign_path, class:"btn btn-default" %></p>    
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>
		
		
	</div>

app/views/static_pages/selection.html.erb
<img src="<%= image_path("bg.png")%>" style="width:100% ; position: fixed;"/>
<div class="row" style="margin:5%;">	
		<div class="col-sm-5" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 50px;
	font-weight: 300;
	color: #FFFFFF;">
        <%= link_to image_tag("invw.png"), new_event_path, class: "images" %>
			</div>
			<div class="col-sm-2" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 150px;
	font-weight: 300;
	color: #FFFFFF;">
				<p></p>
			</div>
			<div class="col-sm-5" style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 50px;
	font-weight: 300;
	color: #FFFFFF; margin-top:20px;">
        <%= link_to image_tag("joiw.png"), list_path, class: "images" %>
			</div>
	</div>
<div class="row" style="margin: 2%; margin-left: -15px;">	
		<div class="col-sm-5" style="text-align:center;">
				<%= link_to 'Be an Inviter', new_event_path, class:"btn btn-default" %>
			</div>
			<div class="col-sm-2" style="text-align:center;">
				<p></p>
			</div>
			<div class="col-sm-5" style="text-align:center;">
				<%= link_to 'Be a Joiner', events_path, class:"btn btn-default" %>
			</div>
	</div>
		
		<div class="col-sm-12">
      </br>
			<p style="text-align:center;font-family: 'Amatic SC', cursive;
	font-size: 80px;
	font-weight: 300;
	color: #FFFFFF;">InstantVite</p>
		</div>
		
		<div class="footer">
			<p>
				InstantVite | FutureHacks 2018
			</p>
		</div>